import type { EntityTypeOption, TimezoneEntry } from '../types/types';

export const PAGE_SIZE = 500;

export const SUPPRESSION_OPTIONS = [
  { value: 'DETECT_PROBLEMS_AND_ALERT', label: 'Detect problems and alert' },
  { value: 'DETECT_PROBLEMS_DONT_ALERT', label: "Detect problems but don't alert" },
  { value: 'DONT_DETECT_PROBLEMS', label: "Don't detect problems" },
];

export const QUICK_ENTITY_TYPES = [
  { value: 'HOST', label: 'Host' },
  { value: 'HOST_GROUP', label: 'Host Group' },
  { value: 'PROCESS_GROUP', label: 'Process Group' },
  { value: 'SERVICE', label: 'Service' },
  { value: 'APPLICATION', label: 'Application' },
  { value: 'OTHER', label: 'Other' },
];

export const ENTITY_TYPES_WITH_UNDERLYING = ['HOST', 'HOST_GROUP', 'PROCESS_GROUP', 'SERVICE'];

export const AUTO_CLEANUP_EXPIRED_TAGS = true;

export const DEFAULT_ENTITY_TYPES: EntityTypeOption[] = [
  { value: 'APPLICATION', label: 'Application' },
  { value: 'APPLICATION_METHOD', label: 'Application Method' },
  { value: 'APPLICATION_METHOD_GROUP', label: 'Application Method Group' },
  { value: 'AUTO_SCALING_GROUP', label: 'Auto Scaling Group' },
  { value: 'AUXILIARY_SYNTHETIC_TEST', label: 'Auxiliary Synthetic Test' },
  { value: 'AWS_APPLICATION_LOAD_BALANCER', label: 'AWS Application Load Balancer' },
  { value: 'AWS_AVAILABILITY_ZONE', label: 'AWS Availability Zone' },
  { value: 'AWS_CREDENTIALS', label: 'AWS Credentials' },
  { value: 'AWS_LAMBDA_FUNCTION', label: 'AWS Lambda Function' },
  { value: 'AWS_NETWORK_LOAD_BALANCER', label: 'AWS Network Load Balancer' },
  { value: 'AZURE_API_MANAGEMENT_SERVICE', label: 'Azure API Management Service' },
  { value: 'AZURE_APPLICATION_GATEWAY', label: 'Azure Application Gateway' },
  { value: 'AZURE_COSMOS_DB', label: 'Azure Cosmos DB' },
  { value: 'AZURE_CREDENTIALS', label: 'Azure Credentials' },
  { value: 'AZURE_EVENT_HUB', label: 'Azure Event Hub' },
  { value: 'AZURE_EVENT_HUB_NAMESPACE', label: 'Azure Event Hub Namespace' },
  { value: 'AZURE_FUNCTION_APP', label: 'Azure Function App' },
  { value: 'AZURE_IOT_HUB', label: 'Azure IoT Hub' },
  { value: 'AZURE_LOAD_BALANCER', label: 'Azure Load Balancer' },
  { value: 'AZURE_MGMT_GROUP', label: 'Azure Management Group' },
  { value: 'AZURE_REDIS_CACHE', label: 'Azure Redis Cache' },
  { value: 'AZURE_REGION', label: 'Azure Region' },
  { value: 'AZURE_SERVICE_BUS', label: 'Azure Service Bus' },
  { value: 'AZURE_SQL_DATABASE', label: 'Azure SQL Database' },
  { value: 'AZURE_SQL_ELASTIC_POOL', label: 'Azure SQL Elastic Pool' },
  { value: 'AZURE_SQL_SERVER', label: 'Azure SQL Server' },
  { value: 'AZURE_STORAGE_ACCOUNT', label: 'Azure Storage Account' },
  { value: 'AZURE_SUBSCRIPTION', label: 'Azure Subscription' },
  { value: 'AZURE_TENANT', label: 'Azure Tenant' },
  { value: 'AZURE_VM', label: 'Azure VM' },
  { value: 'AZURE_VM_SCALE_SET', label: 'Azure VM Scale Set' },
  { value: 'AZURE_WEB_APP', label: 'Azure Web App' },
  { value: 'BROWSER_MONITOR', label: 'Browser Monitor' },
  { value: 'CINDER_VOLUME', label: 'Cinder Volume' },
  { value: 'CLOUD_APPLICATION', label: 'Cloud Application' },
  { value: 'CLOUD_APPLICATION_INSTANCE', label: 'Cloud Application Instance' },
  { value: 'CLOUD_APPLICATION_NAMESPACE', label: 'Cloud Application Namespace' },
  { value: 'CONTAINER_GROUP', label: 'Container Group' },
  { value: 'CONTAINER_GROUP_INSTANCE', label: 'Container Group Instance' },
  { value: 'CUSTOM_APPLICATION', label: 'Custom Application' },
  { value: 'CUSTOM_DEVICE', label: 'Custom Device' },
  { value: 'CUSTOM_DEVICE_GROUP', label: 'Custom Device Group' },
  { value: 'DCRUM_APPLICATION', label: 'DC RUM Application' },
  { value: 'DCRUM_SERVICE', label: 'DC RUM Service' },
  { value: 'DCRUM_SERVICE_INSTANCE', label: 'DC RUM Service Instance' },
  { value: 'DEVICE_APPLICATION_METHOD', label: 'Device Application Method' },
  { value: 'DISK', label: 'Disk' },
  { value: 'DOCKER_CONTAINER_GROUP', label: 'Docker Container Group' },
  { value: 'DOCKER_CONTAINER_GROUP_INSTANCE', label: 'Docker Container Group Instance' },
  { value: 'DYNAMO_DB_TABLE', label: 'DynamoDB Table' },
  { value: 'EBS_VOLUME', label: 'EBS Volume' },
  { value: 'EC2_INSTANCE', label: 'EC2 Instance' },
  { value: 'ELASTIC_LOAD_BALANCER', label: 'Elastic Load Balancer' },
  { value: 'ENVIRONMENT', label: 'Environment' },
  { value: 'ESXI_HOST', label: 'ESXi Host' },
  { value: 'EXTERNAL_SYNTHETIC_TEST_STEP', label: 'External Synthetic Test Step' },
  { value: 'GCP_ZONE', label: 'GCP Zone' },
  { value: 'GEOLOCATION', label: 'Geolocation' },
  { value: 'GEOLOC_SITE', label: 'Geolocation Site' },
  { value: 'GOOGLE_COMPUTE_ENGINE', label: 'Google Compute Engine' },
  { value: 'HOST', label: 'Host' },
  { value: 'HOST_GROUP', label: 'Host Group' },
  { value: 'HTTP_CHECK', label: 'HTTP Check' },
  { value: 'HTTP_CHECK_STEP', label: 'HTTP Check Step' },
  { value: 'HYPERVISOR', label: 'Hypervisor' },
  { value: 'KUBERNETES_CLUSTER', label: 'Kubernetes Cluster' },
  { value: 'KUBERNETES_NODE', label: 'Kubernetes Node' },
  { value: 'KUBERNETES_SERVICE', label: 'Kubernetes Service' },
  { value: 'MOBILE_APPLICATION', label: 'Mobile Application' },
  { value: 'NETWORK_INTERFACE', label: 'Network Interface' },
  { value: 'NEUTRON_SUBNET', label: 'Neutron Subnet' },
  { value: 'OPENSTACK_PROJECT', label: 'OpenStack Project' },
  { value: 'OPENSTACK_REGION', label: 'OpenStack Region' },
  { value: 'OPENSTACK_VM', label: 'OpenStack VM' },
  { value: 'OS', label: 'Operating System' },
  { value: 'PROCESS_GROUP', label: 'Process Group' },
  { value: 'PROCESS_GROUP_INSTANCE', label: 'Process Group Instance' },
  { value: 'QUEUE', label: 'Queue' },
  { value: 'QUEUE_INSTANCE', label: 'Queue Instance' },
  { value: 'RELATIONAL_DATABASE_SERVICE', label: 'Relational Database Service' },
  { value: 'SERVICE', label: 'Service' },
  { value: 'SERVICE_INSTANCE', label: 'Service Instance' },
  { value: 'SERVICE_METHOD', label: 'Service Method' },
  { value: 'SERVICE_METHOD_GROUP', label: 'Service Method Group' },
  { value: 'SWIFT_CONTAINER', label: 'Swift Container' },
  { value: 'SYNTHETIC_LOCATION', label: 'Synthetic Location' },
  { value: 'SYNTHETIC_TEST', label: 'Synthetic Test' },
  { value: 'SYNTHETIC_TEST_STEP', label: 'Synthetic Test Step' },
  { value: 'VIRTUALMACHINE', label: 'Virtual Machine' },
  { value: 'VMWARE_DATACENTER', label: 'VMware Datacenter' },
].sort((a, b) => a.label.localeCompare(b.label));